### ISSUE TITLE
Global loader

### ISSUE THREAD

**Issue by iferres** [daattali/shinycssloaders#42]
Hi, is it possible to add a global loader when certain events occur? With global loader I mean one single loader for a whole page (or many plots/tables). May be these are 2 separate questions: 1) Is it possible to add a global loader for a whole page/tab? And 2) is it possible to deploy them when certain event happens?
Thanks

**Comment by daattali** [comment]
This isn't supported but would be a welcomed PR

**Comment by ismirsehregal** [comment]
You can manually trigger a "global" spinner as described [here](https://github.com/daattali/shinycssloaders/issues/40#issuecomment-578791809).

**Comment by daattali** [comment]
The solution provided by @ismirsehregal can be used. But this package is mostly concerned with adding loader spinners to outputs. In an effort to avoid feature creep, I've decided that we won't support this feature, but there are other packages such as {waiter} that can be used for full-screen spinners.

**Comment by iferres** [comment]
Thank you very much @daattali, really appreciate your effort. But unfortunately I'm no longer working on any shiny project right now where I could test it.

**Comment by ismirsehregal** [comment]
@daattali - it is working fine - thanks!

**Comment by daattali** [comment]
@iferres @ismirsehregal I changed how the full page spinner works. There is no longer a UI function `pageSpinner()`. Now you only need to call `showPageSpinner()` with all the parameters.

I had to do this because otherwise you could only have a single look for the page spinner. Now you can use the page spinner multiple times, with different parameters every time.
