### ISSUE TITLE
Problem when combining shinycssloaders with shinyjs

### ISSUE THREAD

**Issue by gd047** [daattali/shinycssloaders#53]
This is a print screen of a case. The above plot (plot1) is "_withSpinner_". It is hidden by code like the following :

```
    observeEvent(.....
    if(nrow(plot1_df())<1){
      hide("plot1")
    }
    ......
```

However, the animation never dissapears! What is more, it's div lays "above" the tab panels, preventing the choice of another tab! I could do nothing but stop using "withSpinner"

![image](https://user-images.githubusercontent.com/3167917/90416535-463b0280-e0bb-11ea-87e0-fe1a5efa7dfe.png)

**Comment by daattali** [comment]
This is similar to https://github.com/daattali/shinycssloaders/issues/35 but that issue was when using `conditionalPanel()` instead of shinyjs. That was easy to resolve because with conditionalPanel, the entire HTML block that contains both the plot and the loader animation gets hidden. With shinyjs, the plot gets hidden, but the loader animation is not.

Anyway, the solutoin is to wrap the plot  in a `div()` and hide that div, not the plot (that way, the loader is also hidden with shinyjs).

Example:

```
library(shiny)

ui <- fluidPage(
  shinyjs::useShinyjs(),
  actionButton("hide", "hide"),
  actionButton("go", "go"),
  div(id = "plot_container",
      plotOutput("plot") %>% shinycssloaders::withSpinner()
  )
)

server <- function(input, output, session) {
  observeEvent(input$hide, shinyjs::toggle("plot_container"))
  
  output$plot <- output$plot2 <- renderPlot({
    input$go
    Sys.sleep(1)
    plot(rnorm(100))
  })
}

shinyApp(ui, server)
```
